services:
  localstack:
    container_name: localstack_s3
    image: localstack/localstack:3.0.2  # Usando uma versão estável específica
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - ACTIVATE_PRO=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Essencial para o LocalStack funcionar