# Perfil 'docker' ? usar quando a app roda no host conectando aos containers
# Ativar com: --spring.profiles.active=docker em application.properties

# Postgres no container (porta 5433 mapeada do host)
spring.datasource.url=jdbc:postgresql://localhost:5433/GoTicketDB
spring.datasource.username=goticket
spring.datasource.password=goticket

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# LocalStack
spring.cloud.aws.endpoint=http://localhost:4566
