spring.application.name=backendapi
# configs das keys de autenticação

jwt.public.key = classpath:app.pub
jwt.private.key = classpath:app.key

# habilita a execução do data.sql
spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/GoTicketDB
spring.datasource.username=postgres
spring.datasource.password=Cimi2620@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true