spring.application.name=backendapi
# configs das keys de autenticação

jwt.public.key = classpath:app.pub
jwt.private.key = classpath:app.key

# habilita a execução do data.sql
spring.sql.init.mode=always

# habilita a exibição de mensagens de erro contidas nas exceptions
server.error.include-binding-errors=always
server.error.include-message=always

# essa opção abaixo cria a db do zero toda vez que inicia o app, facilitando em dev
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.datasource.url=jdbc:postgresql://localhost:5432/GoTicketDB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true