--
-- Name: tb_admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_admins (
    last_update_date timestamp(6) with time zone NOT NULL,
    register_date timestamp(6) with time zone NOT NULL,
    user_id uuid NOT NULL,
    full_name character varying(255) NOT NULL
);


--
-- Name: tb_batch_allotments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_batch_allotments (
    price numeric(10,2),
    quota integer NOT NULL,
    sold_tickets integer NOT NULL,
    allotment_id bigint NOT NULL,
    batch_id bigint NOT NULL,
    last_update_date timestamp(6) with time zone NOT NULL,
    register_date timestamp(6) with time zone NOT NULL,
    ticket_type_id bigint NOT NULL,
    version bigint
);


--
-- Name: tb_batch_allotments_allotment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_batch_allotments ALTER COLUMN allotment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_batch_allotments_allotment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_clients (
    birth_date date NOT NULL,
    sex integer NOT NULL,
    last_update_date timestamp(6) with time zone NOT NULL,
    register_date timestamp(6) with time zone NOT NULL,
    user_id uuid NOT NULL,
    city character varying(255),
    country character varying(255),
    full_name character varying(255) NOT NULL,
    identity_document character varying(255) NOT NULL,
    neighborhood character varying(255),
    state character varying(255),
    street_address character varying(255),
    street_address_number character varying(255),
    zip_code character varying(255),
    CONSTRAINT tb_clients_sex_check CHECK ((sex = ANY (ARRAY[1, 2])))
);


--
-- Name: tb_eligibility_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_eligibility_types (
    eligibility_type_id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_eligibility_types_eligibility_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_eligibility_types ALTER COLUMN eligibility_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_eligibility_types_eligibility_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_event_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_event_categories (
    category_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL
);


--
-- Name: tb_event_categories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_event_categories ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_event_categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_event_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_event_category (
    category_id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: tb_event_category_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_event_category ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_event_category_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_event_date_sectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_event_date_sectors (
    event_date_id bigint NOT NULL,
    event_date_sector_id bigint NOT NULL,
    event_sector_id bigint NOT NULL,
    last_update_date timestamp(6) with time zone NOT NULL,
    register_date timestamp(6) with time zone NOT NULL
);


--
-- Name: tb_event_date_sectors_event_date_sector_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_event_date_sectors ALTER COLUMN event_date_sector_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_event_date_sectors_event_date_sector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_event_dates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_event_dates (
    end_date timestamp(6) without time zone NOT NULL,
    event_date_id bigint NOT NULL,
    event_id bigint NOT NULL,
    last_update_date timestamp(6) with time zone NOT NULL,
    register_date timestamp(6) with time zone NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    status_id bigint NOT NULL
);


--
-- Name: tb_event_dates_event_date_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_event_dates ALTER COLUMN event_date_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_event_dates_event_date_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_event_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_event_images (
    ordination integer NOT NULL,
    event_id bigint NOT NULL,
    event_image_id bigint NOT NULL,
    s3_key character varying(255) NOT NULL
);


--
-- Name: tb_event_images_event_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_event_images ALTER COLUMN event_image_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_event_images_event_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_event_sectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_event_sectors (
    has_numbered_seats boolean NOT NULL,
    event_id bigint NOT NULL,
    last_update_date timestamp(6) with time zone NOT NULL,
    register_date timestamp(6) with time zone NOT NULL,
    sector_id bigint NOT NULL,
    venue_sector_id bigint NOT NULL,
    description character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: tb_event_sectors_sector_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_event_sectors ALTER COLUMN sector_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_event_sectors_sector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_event_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_event_status (
    status_id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_event_status_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_event_status ALTER COLUMN status_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_event_status_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_event_visibilities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_event_visibilities (
    visibility_id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_event_visibilities_visibility_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_event_visibilities ALTER COLUMN visibility_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_event_visibilities_visibility_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_events (
    age_restriction integer NOT NULL,
    approval_date timestamp(6) with time zone,
    category_id bigint NOT NULL,
    end_date timestamp(6) without time zone NOT NULL,
    event_id bigint NOT NULL,
    last_update_date timestamp(6) with time zone NOT NULL,
    register_date timestamp(6) with time zone NOT NULL,
    sales_start_date timestamp(6) without time zone,
    start_date timestamp(6) without time zone NOT NULL,
    status_id bigint NOT NULL,
    venue_id bigint NOT NULL,
    visibility_id bigint NOT NULL,
    organizer_id uuid NOT NULL,
    description text NOT NULL,
    title character varying(255) NOT NULL
);


--
-- Name: tb_events_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_events ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_organizers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_organizers (
    last_update_date timestamp(6) with time zone,
    register_date timestamp(6) with time zone NOT NULL,
    user_id uuid NOT NULL,
    city character varying(255),
    cnpj character varying(255) NOT NULL,
    country character varying(255),
    legal_name character varying(255) NOT NULL,
    neighborhood character varying(255),
    organizer_name character varying(255) NOT NULL,
    state character varying(255),
    street_address character varying(255),
    street_address_number character varying(255),
    zip_code character varying(255)
);


--
-- Name: tb_refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_refresh_tokens (
    revoked boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    family_id character varying(255) NOT NULL,
    token character varying(255) NOT NULL
);


--
-- Name: tb_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_roles (
    role_id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_status (
    status_id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_status_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_status ALTER COLUMN status_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_status_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_ticket_batches; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_ticket_batches (
    batch_number integer NOT NULL,
    price numeric(10,2) NOT NULL,
    total_tickets integer NOT NULL,
    activation_date timestamp(6) without time zone,
    batch_id bigint NOT NULL,
    event_date_sector_id bigint NOT NULL,
    version bigint
);


--
-- Name: tb_ticket_batches_batch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_ticket_batches ALTER COLUMN batch_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_ticket_batches_batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_ticket_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_ticket_status (
    ticket_status_id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_ticket_status_ticket_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_ticket_status ALTER COLUMN ticket_status_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_ticket_status_ticket_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_ticket_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_ticket_types (
    ticket_type_id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_ticket_types_ticket_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_ticket_types ALTER COLUMN ticket_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_ticket_types_ticket_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_tickets (
    fees_paid numeric(10,2),
    paid_price numeric(10,2) NOT NULL,
    batch_allotment_id bigint NOT NULL,
    eligibility_type_id bigint,
    register_date timestamp(6) with time zone NOT NULL,
    status_id bigint NOT NULL,
    used_date timestamp(6) with time zone,
    buyer_id uuid NOT NULL,
    ticket_id uuid NOT NULL,
    eligibility_document_number character varying(50),
    qr_token character varying(64) NOT NULL,
    holder_document character varying(255) NOT NULL,
    holder_name character varying(255) NOT NULL
);


--
-- Name: tb_user_status; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_user_status (
    status_id bigint NOT NULL,
    name character varying(255)
);


--
-- Name: tb_user_status_status_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_user_status ALTER COLUMN status_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_user_status_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_users (
    role_id bigint NOT NULL,
    status_id bigint NOT NULL,
    user_id uuid NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


--
-- Name: tb_venue_sectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_venue_sectors (
    max_capacity integer NOT NULL,
    last_update_date timestamp(6) with time zone NOT NULL,
    register_date timestamp(6) with time zone NOT NULL,
    sector_id bigint NOT NULL,
    venue_id bigint NOT NULL,
    description character varying(255) NOT NULL,
    map_element_id character varying(255),
    name character varying(255) NOT NULL
);


--
-- Name: tb_venue_sectors_sector_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_venue_sectors ALTER COLUMN sector_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_venue_sectors_sector_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_venues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_venues (
    approval_date timestamp(6) with time zone,
    last_update_date timestamp(6) with time zone NOT NULL,
    register_date timestamp(6) with time zone NOT NULL,
    status_id bigint NOT NULL,
    venue_id bigint NOT NULL,
    organizer_id uuid,
    city character varying(255) NOT NULL,
    cnpj character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    description character varying(255),
    legal_name character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    neighborhood character varying(255) NOT NULL,
    sector_map_s3_key character varying(255),
    state character varying(255) NOT NULL,
    street_address character varying(255) NOT NULL,
    street_address_number character varying(255) NOT NULL,
    zip_code character varying(255) NOT NULL
);


--
-- Name: tb_venues_venue_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_venues ALTER COLUMN venue_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_venues_venue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vw_event_min_details; Type: MATERIALIZED VIEW; Schema: public; Owner: -
--

CREATE MATERIALIZED VIEW public.vw_event_min_details AS
 SELECT e.event_id,
    e.title,
    e.start_date,
    ec.category_id,
    ec.name AS category_name,
    v.name AS venue_name,
    v.city AS venue_city,
    v.state AS venue_state,
    prices.starting_price,
    img.image_keys
   FROM ((((public.tb_events e
     JOIN public.tb_event_categories ec ON ((ec.category_id = e.category_id)))
     JOIN public.tb_venues v ON ((v.venue_id = e.venue_id)))
     LEFT JOIN ( SELECT es.event_id,
            min(
                CASE
                    WHEN ((tt.name)::text = 'FULL'::text) THEN tb.price
                    WHEN ((tt.name)::text = 'HALF'::text) THEN round((tb.price * 0.5), 2)
                    WHEN ((tt.name)::text = 'SOLIDARY'::text) THEN ba.price
                    ELSE NULL::numeric
                END) AS starting_price
           FROM ((((public.tb_event_sectors es
             JOIN public.tb_event_date_sectors eds ON ((eds.event_sector_id = es.sector_id)))
             JOIN public.tb_ticket_batches tb ON ((tb.event_date_sector_id = eds.event_date_sector_id)))
             JOIN public.tb_batch_allotments ba ON ((ba.batch_id = tb.batch_id)))
             JOIN public.tb_ticket_types tt ON ((tt.ticket_type_id = ba.ticket_type_id)))
          GROUP BY es.event_id) prices ON ((prices.event_id = e.event_id)))
     LEFT JOIN ( SELECT tb_event_images.event_id,
            array_agg(tb_event_images.s3_key ORDER BY tb_event_images.ordination) AS image_keys
           FROM public.tb_event_images
          GROUP BY tb_event_images.event_id) img ON ((img.event_id = e.event_id)))
  WHERE ((e.status_id = 2) AND (e.visibility_id = 1))
  WITH NO DATA;

REFRESH MATERIALIZED VIEW vw_event_min_details;

--
-- Name: tb_admins tb_admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_admins
    ADD CONSTRAINT tb_admins_pkey PRIMARY KEY (user_id);


--
-- Name: tb_batch_allotments tb_batch_allotments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_batch_allotments
    ADD CONSTRAINT tb_batch_allotments_pkey PRIMARY KEY (allotment_id);


--
-- Name: tb_clients tb_clients_identity_document_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_clients
    ADD CONSTRAINT tb_clients_identity_document_key UNIQUE (identity_document);


--
-- Name: tb_clients tb_clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_clients
    ADD CONSTRAINT tb_clients_pkey PRIMARY KEY (user_id);


--
-- Name: tb_eligibility_types tb_eligibility_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_eligibility_types
    ADD CONSTRAINT tb_eligibility_types_pkey PRIMARY KEY (eligibility_type_id);


--
-- Name: tb_event_categories tb_event_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_categories
    ADD CONSTRAINT tb_event_categories_pkey PRIMARY KEY (category_id);


--
-- Name: tb_event_categories tb_event_categories_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_categories
    ADD CONSTRAINT tb_event_categories_slug_key UNIQUE (slug);


--
-- Name: tb_event_category tb_event_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_category
    ADD CONSTRAINT tb_event_category_pkey PRIMARY KEY (category_id);


--
-- Name: tb_event_date_sectors tb_event_date_sectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_date_sectors
    ADD CONSTRAINT tb_event_date_sectors_pkey PRIMARY KEY (event_date_sector_id);


--
-- Name: tb_event_dates tb_event_dates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_dates
    ADD CONSTRAINT tb_event_dates_pkey PRIMARY KEY (event_date_id);


--
-- Name: tb_event_images tb_event_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_images
    ADD CONSTRAINT tb_event_images_pkey PRIMARY KEY (event_image_id);


--
-- Name: tb_event_sectors tb_event_sectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_sectors
    ADD CONSTRAINT tb_event_sectors_pkey PRIMARY KEY (sector_id);


--
-- Name: tb_event_status tb_event_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_status
    ADD CONSTRAINT tb_event_status_pkey PRIMARY KEY (status_id);


--
-- Name: tb_event_visibilities tb_event_visibilities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_visibilities
    ADD CONSTRAINT tb_event_visibilities_pkey PRIMARY KEY (visibility_id);


--
-- Name: tb_events tb_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_events
    ADD CONSTRAINT tb_events_pkey PRIMARY KEY (event_id);


--
-- Name: tb_organizers tb_organizers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_organizers
    ADD CONSTRAINT tb_organizers_pkey PRIMARY KEY (user_id);


--
-- Name: tb_refresh_tokens tb_refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_refresh_tokens
    ADD CONSTRAINT tb_refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: tb_refresh_tokens tb_refresh_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_refresh_tokens
    ADD CONSTRAINT tb_refresh_tokens_token_key UNIQUE (token);


--
-- Name: tb_roles tb_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_roles
    ADD CONSTRAINT tb_roles_pkey PRIMARY KEY (role_id);


--
-- Name: tb_status tb_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_status
    ADD CONSTRAINT tb_status_pkey PRIMARY KEY (status_id);


--
-- Name: tb_ticket_batches tb_ticket_batches_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_ticket_batches
    ADD CONSTRAINT tb_ticket_batches_pkey PRIMARY KEY (batch_id);


--
-- Name: tb_ticket_status tb_ticket_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_ticket_status
    ADD CONSTRAINT tb_ticket_status_pkey PRIMARY KEY (ticket_status_id);


--
-- Name: tb_ticket_types tb_ticket_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_ticket_types
    ADD CONSTRAINT tb_ticket_types_pkey PRIMARY KEY (ticket_type_id);


--
-- Name: tb_tickets tb_tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_tickets
    ADD CONSTRAINT tb_tickets_pkey PRIMARY KEY (ticket_id);


--
-- Name: tb_tickets tb_tickets_qr_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_tickets
    ADD CONSTRAINT tb_tickets_qr_token_key UNIQUE (qr_token);


--
-- Name: tb_user_status tb_user_status_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_user_status
    ADD CONSTRAINT tb_user_status_pkey PRIMARY KEY (status_id);


--
-- Name: tb_users tb_users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT tb_users_email_key UNIQUE (email);


--
-- Name: tb_users tb_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT tb_users_pkey PRIMARY KEY (user_id);


--
-- Name: tb_venue_sectors tb_venue_sectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_venue_sectors
    ADD CONSTRAINT tb_venue_sectors_pkey PRIMARY KEY (sector_id);


--
-- Name: tb_venues tb_venues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_venues
    ADD CONSTRAINT tb_venues_pkey PRIMARY KEY (venue_id);


--
-- Name: tb_batch_allotments uq_batch_allotment_type; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_batch_allotments
    ADD CONSTRAINT uq_batch_allotment_type UNIQUE (batch_id, ticket_type_id);


--
-- Name: tb_event_date_sectors uq_event_date_sector; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_date_sectors
    ADD CONSTRAINT uq_event_date_sector UNIQUE (event_date_id, event_sector_id);


--
-- Name: tb_ticket_batches uq_ticket_batch_date_sector_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_ticket_batches
    ADD CONSTRAINT uq_ticket_batch_date_sector_number UNIQUE (event_date_sector_id, batch_number);


--
-- Name: idx_batch_allotments_available; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_batch_allotments_available ON public.tb_batch_allotments USING btree (batch_id, ticket_type_id) WHERE (quota > sold_tickets);


--
-- Name: idx_event_date_sectors_event_sector; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_date_sectors_event_sector ON public.tb_event_date_sectors USING btree (event_sector_id);


--
-- Name: idx_event_images_event_ordination; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_images_event_ordination ON public.tb_event_images USING btree (event_id, ordination);


--
-- Name: idx_events_status_visibility; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_events_status_visibility ON public.tb_events USING btree (status_id, visibility_id);


--
-- Name: idx_refresh_family; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_family ON public.tb_refresh_tokens USING btree (family_id);


--
-- Name: idx_ticket_batches_date_sector_price; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ticket_batches_date_sector_price ON public.tb_ticket_batches USING btree (event_date_sector_id, price);


--
-- Name: idx_vw_event_min_details_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_vw_event_min_details_date ON public.vw_event_min_details USING btree (start_date);


--
-- Name: uq_vw_event_min_details_event; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_vw_event_min_details_event ON public.vw_event_min_details USING btree (event_id);


--
-- Name: tb_tickets fk1oiy4107ubsj5ns1rny9d1q4t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_tickets
    ADD CONSTRAINT fk1oiy4107ubsj5ns1rny9d1q4t FOREIGN KEY (status_id) REFERENCES public.tb_ticket_status(ticket_status_id);


--
-- Name: tb_organizers fk1uv4tbh79u85bfql1vxrltrua; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_organizers
    ADD CONSTRAINT fk1uv4tbh79u85bfql1vxrltrua FOREIGN KEY (user_id) REFERENCES public.tb_users(user_id);


--
-- Name: tb_users fk2bwdk5w4y4ehty96tvk2w66ow; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT fk2bwdk5w4y4ehty96tvk2w66ow FOREIGN KEY (role_id) REFERENCES public.tb_roles(role_id);


--
-- Name: tb_batch_allotments fk2m9tjqgj55qafv35tu9ef9n1c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_batch_allotments
    ADD CONSTRAINT fk2m9tjqgj55qafv35tu9ef9n1c FOREIGN KEY (batch_id) REFERENCES public.tb_ticket_batches(batch_id);


--
-- Name: tb_tickets fk3w4cjw50mc964qf8lhmtljs08; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_tickets
    ADD CONSTRAINT fk3w4cjw50mc964qf8lhmtljs08 FOREIGN KEY (buyer_id) REFERENCES public.tb_clients(user_id);


--
-- Name: tb_tickets fk44tmlpcxu7p9qr0e3rc49vd5f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_tickets
    ADD CONSTRAINT fk44tmlpcxu7p9qr0e3rc49vd5f FOREIGN KEY (eligibility_type_id) REFERENCES public.tb_eligibility_types(eligibility_type_id);


--
-- Name: tb_event_date_sectors fk4jdyssnqkvvb7hqy9ht0hxkmd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_date_sectors
    ADD CONSTRAINT fk4jdyssnqkvvb7hqy9ht0hxkmd FOREIGN KEY (event_date_id) REFERENCES public.tb_event_dates(event_date_id);


--
-- Name: tb_event_date_sectors fk4y7k0nat520sp86e2rp5mpnjm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_date_sectors
    ADD CONSTRAINT fk4y7k0nat520sp86e2rp5mpnjm FOREIGN KEY (event_sector_id) REFERENCES public.tb_event_sectors(sector_id);


--
-- Name: tb_event_dates fk7ffmkfnu804i9txdad5t9t6gf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_dates
    ADD CONSTRAINT fk7ffmkfnu804i9txdad5t9t6gf FOREIGN KEY (status_id) REFERENCES public.tb_event_status(status_id);


--
-- Name: tb_venues fk9857amakasseelgdy71regljg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_venues
    ADD CONSTRAINT fk9857amakasseelgdy71regljg FOREIGN KEY (status_id) REFERENCES public.tb_status(status_id);


--
-- Name: tb_ticket_batches fkairurlvn358rx3ehst66ghdx3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_ticket_batches
    ADD CONSTRAINT fkairurlvn358rx3ehst66ghdx3 FOREIGN KEY (event_date_sector_id) REFERENCES public.tb_event_date_sectors(event_date_sector_id);


--
-- Name: tb_event_sectors fkcmonngf02d5pv4nn1o9pw2qd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_sectors
    ADD CONSTRAINT fkcmonngf02d5pv4nn1o9pw2qd FOREIGN KEY (venue_sector_id) REFERENCES public.tb_venue_sectors(sector_id);


--
-- Name: tb_users fkdm95hp9atjt6n2juwp8fmgvb8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_users
    ADD CONSTRAINT fkdm95hp9atjt6n2juwp8fmgvb8 FOREIGN KEY (status_id) REFERENCES public.tb_status(status_id);


--
-- Name: tb_event_images fki5jiuv0co5bt33wjstrf58wkr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_images
    ADD CONSTRAINT fki5jiuv0co5bt33wjstrf58wkr FOREIGN KEY (event_id) REFERENCES public.tb_events(event_id);


--
-- Name: tb_refresh_tokens fkidkw733t1mfbs1psj59n76oj4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_refresh_tokens
    ADD CONSTRAINT fkidkw733t1mfbs1psj59n76oj4 FOREIGN KEY (user_id) REFERENCES public.tb_users(user_id);


--
-- Name: tb_events fkjqbevkxd914m917hy8t65qha2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_events
    ADD CONSTRAINT fkjqbevkxd914m917hy8t65qha2 FOREIGN KEY (venue_id) REFERENCES public.tb_venues(venue_id);


--
-- Name: tb_tickets fkkn9rqko86ykpbjgk6xl9s4q6d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_tickets
    ADD CONSTRAINT fkkn9rqko86ykpbjgk6xl9s4q6d FOREIGN KEY (batch_allotment_id) REFERENCES public.tb_batch_allotments(allotment_id);


--
-- Name: tb_venues fkl2tavi69v07ld6o9oq6sx4229; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_venues
    ADD CONSTRAINT fkl2tavi69v07ld6o9oq6sx4229 FOREIGN KEY (organizer_id) REFERENCES public.tb_organizers(user_id);


--
-- Name: tb_events fkmvkcr6bwfuvo287i7bax1kvev; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_events
    ADD CONSTRAINT fkmvkcr6bwfuvo287i7bax1kvev FOREIGN KEY (organizer_id) REFERENCES public.tb_organizers(user_id);


--
-- Name: tb_admins fkn37vprty78iyfnymc7yhckjqy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_admins
    ADD CONSTRAINT fkn37vprty78iyfnymc7yhckjqy FOREIGN KEY (user_id) REFERENCES public.tb_users(user_id);


--
-- Name: tb_batch_allotments fkofsfj30vdofb6pw3y1hoby0nh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_batch_allotments
    ADD CONSTRAINT fkofsfj30vdofb6pw3y1hoby0nh FOREIGN KEY (ticket_type_id) REFERENCES public.tb_ticket_types(ticket_type_id);


--
-- Name: tb_clients fkon6me4fd42ira6ev2fm308yuf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_clients
    ADD CONSTRAINT fkon6me4fd42ira6ev2fm308yuf FOREIGN KEY (user_id) REFERENCES public.tb_users(user_id);


--
-- Name: tb_events fkp7ain3p481wdqcsmw3d9m9yaw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_events
    ADD CONSTRAINT fkp7ain3p481wdqcsmw3d9m9yaw FOREIGN KEY (visibility_id) REFERENCES public.tb_event_visibilities(visibility_id);


--
-- Name: tb_venue_sectors fkpep2g4wpxahd24ef7qnrsibr1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_venue_sectors
    ADD CONSTRAINT fkpep2g4wpxahd24ef7qnrsibr1 FOREIGN KEY (venue_id) REFERENCES public.tb_venues(venue_id);


--
-- Name: tb_event_dates fkr1r7ndx2viftj1b5nf3rl6h0g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_dates
    ADD CONSTRAINT fkr1r7ndx2viftj1b5nf3rl6h0g FOREIGN KEY (event_id) REFERENCES public.tb_events(event_id);


--
-- Name: tb_event_sectors fkrelmbrhjrkcwpi3atvnw17yj4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_event_sectors
    ADD CONSTRAINT fkrelmbrhjrkcwpi3atvnw17yj4 FOREIGN KEY (event_id) REFERENCES public.tb_events(event_id);


--
-- Name: tb_events fkt1bbhv1vtq3q3xgjb7fkghv3w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_events
    ADD CONSTRAINT fkt1bbhv1vtq3q3xgjb7fkghv3w FOREIGN KEY (category_id) REFERENCES public.tb_event_categories(category_id);


--
-- Name: tb_events fktrj454fb2vdlr48bau0xsx33s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_events
    ADD CONSTRAINT fktrj454fb2vdlr48bau0xsx33s FOREIGN KEY (status_id) REFERENCES public.tb_event_status(status_id);



